### PR TITLE
Fix merging of process.env in Node 4+

### LINKED ISSUE #63: BUG: builder envs does not get same base env ($PATH etc.) as builder run on Node 4+
If my `test` command is something like `mocha` or `wdio` that comes from `node_modules`, `builder run test` works fine, but `builder envs test --envs-path=envs.json` spits out:

```
/bin/sh: mocha: command not found
```

Builder should start out with whatever `$PATH` additions come standard with `builder run`, then merge in stuff from `envs` on top of that.

(In case it matters: I'm using Builder just for its task running features, without an archetype.)

### PR DESCRIPTION
**Pull request by exogen**
`builder envs` did not work on Node 4+ because `_.merge` was behaving differently due to `process.env` no longer being a plain object. This clones `shOpts` (which contains `env`) so that merge works as expected.

I considered `_.toPlainObject(process.env)` in `environment.js` in place of this fix, to fix the problem at its source. That worked, but I was fearful of the implications as Environment explicitly says that `env` is "environment object to mutate" – and using that fix we'd no longer be mutating `process.env` but a copy.

Fixes #63

/cc @ryan-roemer

### CODE REVIEW

File: lib/runner.js [hunk 1]
```diff
@@ -228,7 +228,9 @@ module.exports = {
     log.info("envs", "Starting with queue size: " + chalk.magenta(queue || "unlimited"));
     map(function (taskEnv, cb) {
       // Add each specific set of environment variables.
-      var taskShOpts = _.merge({}, shOpts, { env: taskEnv });
+      // Clone `shOpts` to turn `env` into a plain object: in Node 4+
+      // `process.env` is a special object which changes merge behavior.
+      var taskShOpts = _.merge(_.cloneDeep(shOpts), { env: taskEnv });
```
Comment (exogen) [inline lib/runner.js]: I wanted to use `_.toPlainObject(shOpts)` for clarify, but it doesn't work because `shOpts` itself *is* a plain object; the bogus `process.env` still gets through (plain-ness isn't recursive apparently).

**Comment by ryan-roemer** [comment]
@exogen -- Awesome. Thanks!

**Comment by ryan-roemer** [comment]
Released as `builder@2.3.1`
