### PR TITLE
Change to more permissive sibling dependency inference.

### LINKED ISSUE #30: BUG: on npm 2 `builder postinstall` fails if builder package includes another builder package
On repos like axis that are on builder infrastructure, `npm install` will fail on `builder postinstall` if these packages include other builder packages. 

failing CI in this PR is an example:
https://github.com/FormidableLabs/victory-axis/pull/40
`victory-label` is using builder

### PR DESCRIPTION
**Pull request by ryan-roemer**
Fixes #30 

* Infer sibiling dependencies as a fallback if installed from NPM at all (v3 or v2)
* Also throw in a `require.resolve` as another fallback method.

/cc @exogen @boygirl

### CODE REVIEW

**Comment by ryan-roemer** [comment]
I have a successful local install of `victory-axis` using this version for both npm v2 and npm v3.

**Comment by boygirl** [comment]
awesome! can you please do a version bump with this fix?

**Comment by ryan-roemer** [comment]
@exogen -- I'm going to merge to get @boygirl going and while I'm actually available. Would love a post-merge review from you!

File: lib/config.js [hunk 1]
```diff
@@ -81,16 +87,44 @@ Config.prototype._loadArchetypeScripts = function (name) {
...
+    } catch (err) {
+      /*eslint-disable no-empty*/
     }
   }
+
+  try {
+    // Require resolve it
+    var modPath = require.resolve(name);
+    pkgPath = path.join(modPath, "package.json");
+    return require(pkgPath);
```
Comment (exogen) [inline lib/config.js]: This will break if the archetype has a `main` file (our current archetype doesn't, but I don't think we should break here if an archetype has one for some reason). For example when I try this on `lodash`:

```js
> require("path").join(require.resolve("lodash"), "package.json")
'/Users/brianbeck/Projects/Tests/npm-test/node_modules/lodash/dist/lodash.js/package.json'
```

Also, is there a good reason not to just use this as the one-and-only way? I really believe that needing to crawl up the tree to find the archetype will end up being the common case, not an edge case.

**Comment by ryan-roemer** [comment]
Released as `builder@2.1.2`.
