### PR TITLE
BUG: Fix PATH/NODE_PATH resolution order.

### LINKED ISSUE #47: Builder scripts using global `npm` dependencies instead of locals
Opening another ticket here per @boygirl 's request... See FormidableLabs/victory#97 for more details & examples.

While I was working on Victory, I discovered that `builder` scripts which call node binaries like `babel` end up using the globally installed versions of those binaries, rather than the local versions in `node_modules`. This is contrary to the behavior of regular old `npm` scripts which use the local versions. This can cause major problems and build inconsistencies if the user's global module version does not match the local version.

### PR DESCRIPTION
**Pull request by ryan-roemer**
Fixes #47 

We now have a more sensible PATH / NODE_PATH resolution order.

Also:

* Update links on HISTORY
* Minor flags fix for `builder run`

/cc @dandelany @boygirl @exogen @chaseadamsio 

@dandelany @boygirl @exogen -- Can one of you try this out in an erroring Victory repo? Thanks!

### CODE REVIEW

File: lib/task.js [hunk 1]
```diff
@@ -142,7 +142,7 @@ Task.prototype.run = function (callback) {
 
   var env = this._env.env; // Raw environment object.
   var task = this.getCommand(this._command);
-  var flags = args.concurrent(this.argv);
+  var flags = args.run(this.argv);
```
Comment (ryan-roemer) [inline lib/task.js]: BUGFIX

**Comment by dandelany** [comment]
Just checked out this branch and it does indeed fix the error I was seeing. Running `babel --version` in the builder task now correctly shows the local `node_modules` babel version. Also did a quick code review and everything looks fine :+1: . Thanks!
