### PR TITLE
Configurable log levels for builder itself.

### LINKED ISSUE #6: Feature: Configurable log levels.
* [x] Talk with Ryan about whether or not we want to abstract out a `builder-logger` package (for use in `builder-init` and maybe `builder-support`.
* [x] Talk with Ryan about the "bootstrap problem" with using `argv` values for log messages that are only available _after_ we've imported / run a lot of code.
* [x] Implement configurable log levels.
* [x] Update docs for flags (likely `--log-level` or something)
* [x] Disable logging for tests.
* [x] Add tests of the logger.

### LINKED ISSUE #66: Feature: Set log level to "none" during tests.
Writing tests for the `init` task and one of the things I'd like is to silence logs in testing, except for when there's a reason to test the logger, something like this maybe?

```
var testCheck = function (callback) {
  if (process.env.NODE_ENV === "test" && !process.env.TEST_LOGGER) { return; }
  callback();
};

....

  info: function (type, msg) {
    testCheck(function () {
      cons.log([chalk.green(wrapType(type)), msg].join(" "));
    });
  },

  warn: function (type, msg) {
    testCheck(function () {
      cons.warn([chalk.yellow(wrapType(type)), msg].join(" "));
    });
  },

  error: function (type, msg) {
    testCheck(function () {
      cons.error([chalk.red(wrapType(type)), msg].join(" "));
    });
  }
```

### PR DESCRIPTION
**Pull request by ryan-roemer**
* Refactor `builder.js` to pass a buffer of messages to builder to be
  later logged.
* Refactor to queue up log statements until `log.setLevel()` is called. The
  issue we're solving is logging in "./environment" when environment is
  needed to determine what level to log at.
* Adds `--log-level=info|warn|error|none` flag. Fixes #6
* Adds `--quiet` flag as alias for `--log-level=none`.
* Adds env variable `_BUILDER_ARGS_LOG_LEVEL=info|warn|error|none` to also
  control.
* Add tests and docs.

These new controls should allow us to easily set things for test commands. Closes #66

**Note**: I'm not totally sure this won't break in earlier `builder` global installs. We may need to educate folks generally to update if we see any errors for `setLevel()` not being defined / a function.

/cc @chaseadamsio @shakefon @zachhale @coopy

### CODE REVIEW

File: bin/builder-core.js [hunk 1]
```diff
@@ -14,6 +14,7 @@ var log = require("../lib/log");
  * @param {Object}    [opts]      Options object
  * @param {Object}    [opts.env]  Environment object to mutate (Default `process.env`)
  * @param {Array}     [opts.argv] Arguments array (Default: `process.argv`)
+ * @param {Array}     [opts.msgs] Array of log messages.
```
Comment (baer) [inline bin/builder-core.js]: Am I correct in understanding that these are not log messages but message templates?

File: lib/log.js [hunk 2]
```diff
@@ -1,31 +1,101 @@
 "use strict";
 
-var chalk = require("chalk");
```
Comment (baer) [inline lib/log.js]: I like chalk... Why take this out?

Comment (baer) [inline lib/log.js]: nm, I see that it's required at the bottom.

File: bin/builder-core.js (hunk 1 above)
Comment (ryan-roemer) [inline bin/builder-core.js]: Array of `{ level, type, msg }`. I'll update the comment.

File: lib/log.js [hunk 3]
```diff
@@ -1,31 +1,101 @@
...
+
+    // Statefully set level.
+    env._BUILDER_ARGS_LOG_LEVEL = level;
+    log._level = LEVELS[level];
+    if (typeof log._level === "undefined") {
+      throw new Error("Unknown log level: " + level);
+    }
+
+    // Drain message queue.
+    if (log._queue) {
```
Comment (baer) [inline lib/log.js]: Should be a function!

Comment (ryan-roemer) [inline lib/log.js]: Can you explain more?

File: lib/log.js [hunk 4]
```diff
@@ -1,31 +1,101 @@
...
+  _logger: function () {
+    return console;
   },
 
-  error: function (type, msg) {
-    this._logger().error([chalk.red(wrapType(type)), msg].join(" "));
+  _wrapper: function (level, color, type, msg) { // eslint-disable-line max-params
+    // Queue if level is unset.
+    if (typeof log._level === "undefined") {
+      log._queue = log._queue || [];
```
Comment (baer) [inline lib/log.js]: Above you're setting `log._queue = null`. Instead why don't you just drain the queue by doing:
```
log._queue = map(function (obj) {
  log[obj.level](obj.type, obj.msg)
});
```

which will set it to `[]` since that's what you want anyway.

File: lib/log.js [hunk 5]
```diff
@@ -1,31 +1,101 @@
...
+    }
+
+    // Should only get to here, _after_ `builder-core.js` is imported.
+    // Check if logging at this integer level.
+    if (LEVELS[level] < log._level) {
+      return;
+    }
+
+    // Lazy require
+    var chalk = require("chalk"); // eslint-disable-line global-require
```
Comment (baer) [inline lib/log.js]: What's the reason for this?

File: lib/log.js [hunk 6]
```diff
@@ -1,31 +1,101 @@
...
+
+    // Call directly once level is set.
+    // This is also used to drain the queue.
+    log._logger()[level]([chalk[color](wrapType(type)), msg].join(" "));
```
Comment (baer) [inline lib/log.js]: Can this be extracted into a named function - it's kinda hard to understand what's happening here.

**Comment by baer** [comment]
Looks goo! One small code change and a few style comments but otherwise :+1:

File: lib/log.js (hunk 3 above)
Comment (baer) [inline lib/log.js]:
```js
var drainQueue = function drainQueue() {
  ...
}
```

I just have a soft spot for decomposing where possible. If I see a comment above a block of code that effectively "names" it I always think it would be better to extract into a separate function.

File: lib/log.js (hunk 4 above)
Comment (ryan-roemer) [inline lib/log.js]: That would end up with an array of undefineds:

```js
["foo", "bar"].map(function () {})
// => [undefined, undefined]
```

File: lib/log.js (hunk 5 above)
Comment (ryan-roemer) [inline lib/log.js]: I thought I needed to lazy load for conflicts with global installed builder, but it actually shouldn't work that way since things relatively import to their own files. I'm reverting this and the other one.

File: lib/log.js (hunk 6 above)
Comment (ryan-roemer) [inline lib/log.js]: Not really (?)

It would be something like:

```js
_actualLog: function (level, color, type, msg) {
  log._logger()[level]([chalk[color](wrapType(type)), msg].join(" "));
}
```

which is already identical to the signature of `_wrapper` here. This line is essentially, _what_ the wrapper function does...

Comment (exogen) [inline lib/log.js]: New function wouldn't help but pulling out some of those intermediate values would help (I count 6 in one line which does make for a difficult read). Maybe just pull out the main one:

```js
var formattedMsg = [chalk[color](wrapType(type)), msg].join(" ");
log._logger()[level](formattedMsg);
```

**Comment by ryan-roemer** [comment]
@baer @zachhale -- Ready for re-review!

File: lib/log.js (hunk 6 above)
Comment (ryan-roemer) [inline lib/log.js]: Good suggestion @exogen ! Added in https://github.com/FormidableLabs/builder/commit/ffcd96c597bc1b39974c90924de4cc98ed0f3ef1

**Comment by zachhale** [comment]
Assuming it works, looks good to me! @baer?

File: bin/builder-core.js [hunk 7]
```diff
@@ -14,6 +14,7 @@ var log = require("../lib/log");
  * @param {Object}    [opts]      Options object
  * @param {Object}    [opts.env]  Environment object to mutate (Default `process.env`)
  * @param {Array}     [opts.argv] Arguments array (Default: `process.argv`)
+ * @param {Array}     [opts.msgs] Array of log messages (`{ level, type, msg }`)
```
Comment (baer) [inline bin/builder-core.js]: This might be more clear as "message-templates" or something since these are not JUST messages but that's just a personal preference

File: bin/builder-core.js [hunk 8]
```diff
@@ -38,6 +45,11 @@ module.exports = function (opts, callback) {
     runner: runner
   });
 
+  // Drain messages if any.
+  (opts.msgs || []).forEach(function (obj) {
```
Comment (baer) [inline bin/builder-core.js]: Isn't this 1:1 with your _drainQueue method? Also, how does this "Drain" if `opts.msgs` remains the same after this runs

Comment (ryan-roemer) [inline bin/builder-core.js]: I've added a longer commentary of how we really have two different message queues -- https://github.com/FormidableLabs/builder/commit/6e9b658b1ee347b9869d325a45185cd340cca540

File: lib/log.js [hunk 9]
```diff
@@ -1,31 +1,100 @@
...
+   * @returns {void}
+   */
+  setLevel: function (opts) {
+    opts = opts || {};
+    var env = opts.env && opts.env.env || process.env;
+
+    // Try to determine log level from environment.
+    var level = env._BUILDER_ARGS_LOG_LEVEL;
+
+    // If not, determine log level from command line.
```
Comment (baer) [inline lib/log.js]: As always, if it were me I'd pull this into a `getLevel` method.

```
var getLevel = function getLevel(level) {
  if (level) { return level; }
  
  var parsed = args.general(opts.argv);
  return parsed.quiet === true ? "none" : parsed.logLevel;
}
```

You could also make it a class method if you'd prefer.

File: bin/builder-core.js (hunk 8 above)
Comment (ryan-roemer) [inline bin/builder-core.js]: I could expose an `log.addQueue(opts.msgs)` and call before the `setLevel`, but I kind of like the manual draining here for the barrier between `builder.js` and `builder-core.js`

File: lib/log.js [hunk 10]
```diff
@@ -1,31 +1,100 @@
...
+    if (!level) {
+      var parsed = args.general(opts.argv);
+      level = parsed.quiet === true ? "none" : parsed.logLevel;
+    }
+
+    // Statefully set level.
```
Comment (baer) [inline lib/log.js]: Same Same :)

File: lib/log.js [hunk 11]
```diff
@@ -1,31 +1,100 @@
...
+    env._BUILDER_ARGS_LOG_LEVEL = level;
+    log._level = LEVELS[level];
+    if (typeof log._level === "undefined") {
+      throw new Error("Unknown log level: " + level);
+    }
+
+    // Drain message queue.
```
Comment (baer) [inline lib/log.js]: This comment is now extraneous

File: .eslintrc-server-test [hunk 12]
```diff
@@ -11,3 +11,4 @@ globals:
 rules:
   no-unused-expressions: 0  # Disable for Chai expression assertions.
   max-nested-callbacks: 0   # Disable for nested describes.
+  max-statements: [2, 20]   # More statements allowed in tests.
```
Comment (baer) [inline .eslintrc-server-test]: :-1: If you extract all of those functions you won't need this "ignore"

File: lib/log.js (hunk 9 above)
Comment (ryan-roemer) [inline lib/log.js]: I don't think we need that level of decomposition to take a single function of 10 lines to 2 of 5 lines when we're never going to call them separately. Can leave to future refactor when needed.

**Comment by baer** [comment]
A few style things but other than that this is airtight. :+1:

File: .eslintrc-server-test (hunk 12 above)
Comment (ryan-roemer) [inline .eslintrc-server-test]: Nope. :smile:  You're looking at the _test_ eslint, which is better with the disable because of all the mock fs / state / asserts I need for quasi-functional tests.

Comment (baer) [inline .eslintrc-server-test]: Oops - you're right. Sorry about this distraction.

... backing away slowly ...

Comment (ryan-roemer) [inline .eslintrc-server-test]: haha, no worries

File: lib/log.js (hunk 9 above)
Comment (baer) [inline lib/log.js]: ¯\_(ツ)_/¯ - couldn't you say that about almost every refactor. This is a style/discipline preference and it allows for each thing to be tested independently but practically speaking you're right. In cases like this I'd have to say "the author is always right."

**Comment by coopy** [comment]
Posthumous :+1: – nice work ;)
